name: Call API every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API with insecure SSL
        run: |
          curl -k -X GET "https://cred-testapi.transmonqa.in:9443/brcp"
